=== concatgit/fileXML/XSD bai 1/src/luyentap/thuvien.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:complexType name="sachType">
        <xs:sequence>
            <xs:element name="tensach" type="xs:string"/>
            <xs:element name="theloai" type="xs:string"/>
            <xs:element name="sotrang">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="50"/>
                        <xs:maxInclusive value="400"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="masach" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:maxLength value="6"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="nhaxbType">
        <xs:sequence>
            <xs:element name="sach" type="sachType" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="tennxb">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="GiÃ¡o d?c"/>
                    <xs:enumeration value="Tu?i tr?"/>
                    <xs:enumeration value="Khoa h?c k? thu?t"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="thuvienType">
        <xs:sequence>
            <xs:element name="nhaxb" type="nhaxbType" maxOccurs="10"/>
        </xs:sequence>
        <xs:attribute name="tentv" type="xs:string"></xs:attribute>
    </xs:complexType>
    <xs:element name="thuvien" type="thuvienType"></xs:element>
</xs:schema>

=== concatgit/fileXML/XSD bai 1/src/luyentap/luyentap.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="thuvien.xsl" ?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<thuvien
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='thuvien.xsd' tentv="Khu A Dai Hoc Cong Nghiep">
    <nhaxb tennxb="GiÃ¡o d?c">
        <sach masach="S001">
            <tensach>Tin van phong</tensach>
            <theloai>Tin hoc</theloai>
            <sotrang>50</sotrang>
        </sach>
        <sach masach="S002">
            <tensach>Ke toan doanh nghiep</tensach>
            <theloai>Kinh te</theloai>
            <sotrang>180</sotrang>
        </sach>
        <sach masach="S003">
            <tensach>Tai chinh kinh doanh</tensach>
            <theloai>Kinh te</theloai>
            <sotrang>220</sotrang>
        </sach>
    </nhaxb>
    <nhaxb tennxb="Khoa h?c k? thu?t">
        <sach masach="S004">
            <tensach>Chinh kich</tensach>
            <theloai>Van hoc</theloai>
            <sotrang>80</sotrang>
        </sach>
        <sach masach="S005">
            <tensach>Ke dao mo</tensach>
            <theloai>Tam ly</theloai>
            <sotrang>160</sotrang>
        </sach>
        <sach masach="S006">
            <tensach>Giao nhon</tensach>
            <theloai>Lich su</theloai>
            <sotrang>110</sotrang>
        </sach>
    </nhaxb>
</thuvien>
